//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form02 {
	
	
	public partial class ErrorHandle {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label id_label;
		
		protected System.Web.UI.WebControls.DropDownList id_dropDown;
		
		protected System.Web.UI.WebControls.Label id_label2;
		
		protected System.Web.UI.WebControls.HyperLink id_link;
	}
}
